### ISSUE TITLE
Proper Releases

### ISSUE THREAD

**Issue by zeropointnothing** [0hStormy/bnap4000#1]
Hello!

Currently, your releases utilizes a shell script that uses pip to install required dependencies and then create the appropriate folders and files.

This will not work on many Linux systems due to the conflicting nature of Pip with package managers.

If it runs at all, Pip will most likely refuse installation because of this conflict and the script will fail.
![image](https://github.com/user-attachments/assets/7543df2d-c72d-417f-99a9-71be6ee405cb)

You should instead use a packaging module (such as pyinstaller or nuitka) to make bnap4000 executable, then distribute it via the Releases tab. Alternatively, you could utilize Python's `venv` module to create a virtual environment where Pip does exist and can properly install packages. This would require you to create a script in place of bnap4000's main file which starts the virtual environment, launches the program then properly exits it, however.

**Comment by 0hStormy** [comment]
Alright, I'll look into that.

**Comment by 0hStormy** [comment]
Done, v24.11.2 now has a binary!
