### ISSUE TITLE
[BUG] - Potentially Missing Fonts? 

### ISSUE THREAD

**Issue by zeropointnothing** [0hStormy/bnap4000#4]
Hello!

I'm not sure if you're already aware of this, but I would like to bring it to your attention.

Because of bnap4000's text-based nature, please make sure to include the required fonts somewhere (probably README) to properly display the new TUI. Otherwise, users without these fonts (such as myself), will not see the TUI rendered properly.

![Screenshot_20241215_224759](https://github.com/user-attachments/assets/8329a98a-0555-4697-b415-2f7c859e7ae9)

(A tip for you as well: If you would like to avoid bug reports as quick as these, I would recommend adopting a branch based development cycle, where you separate `main` from your active dev work, to avoid bugs like this affecting people using source code as quickly. Of course, you may already know this, just tossing it out.)

**Comment by 0hStormy** [comment]
I'm aware of this, I'll add a nerd font toggle when I get home.

**Comment by 0hStormy** [comment]
Fixed in https://github.com/0hStormy/bnap4000/commit/95d46c73d0724fa08912b37763668fb32e07cd15, if you want the icons you'll need a Nerd Font, if you don't want them bnap4000 will just use whatever is in standard ANSI for icons
